#https://www.youtube.com/watch?v=A5dE25ANU0k&t=269s

from youtube_transcript_api import YouTubeTranscriptApi

# YouTubeTranscriptApi.get_transcript('A5dE25ANU0k')
# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.get_transcript('A5dE25ANU0k')

# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        # transcript.video_id,
        # transcript.language,
        # transcript.language_code,
        # whether it has been manually created or generated by YouTube
        # transcript.is_generated,
        # whether this transcript can be translated or not
        # transcript.is_translatable,
        # a list of languages the transcript can be translated to
        # transcript.translation_languages,
        transcript['text']
    )

    # fetch the actual transcript data
    # print(transcript.fetch())

    # translating the transcript will return another transcript object
    # print(transcript.translate('en').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
# transcript = transcript_list.find_transcript(['de', 'en'])  

# or just filter for manually created transcripts  
# transcript = transcript_list.find_manually_created_transcript(['de', 'en'])  

# or automatically generated ones  
# transcript = transcript_list.find_generated_transcript(['de', 'en'])
